### ISSUE TITLE
uint not defined in Visual C++

### ISSUE THREAD

**Issue by micuat** [yusuketomoto/ofxNumpy#1]
`uint` -> `unsigned int` at
https://github.com/yusuketomoto/ofxNumpy/blob/master/src/ofxNumpy.h#L82
https://github.com/yusuketomoto/ofxNumpy/blob/master/src/ofxNumpy.h#L83
and it works (zlib has to be installed by NuGet).

**Comment by yusuketomoto** [comment]
thanks for issue.
fixed it.

**Comment by micuat** [comment]
Thanks! If I have time I'll write a readme for Visual Studio and an example.
